include: 'https://gitlab.gnome.org/GNOME/citemplates/-/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - check
  - test
  - deploy

.vars_nightly:
  variables:
    MANIFEST_PATH: "build-aux/com.adrienplazas.Metronome.Devel.json"
    FLATPAK_MODULE: "metronome"
    APP_ID: "com.adrienplazas.Metronome.Devel"

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  stage: check
  image: "rust:slim"
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check

build@x86_64:
  extends:
    - .flatpak@x86_64
    - .vars_nightly
  variables:
    BUNDLE: "metronome-nightly-x86_64.flatpak"

build@aarch64:
  extends:
    - .flatpak@aarch64
    - .vars_nightly
  variables:
    BUNDLE: "metronome-nightly-aarch64.flatpak"
  allow_failure: true

# Publish the nightly version
# Only on main
publish_nightly@x86_64:
  extends: .publish_nightly
  needs: ['build@x86_64']

publish_nightly@aarch64:
  extends: .publish_nightly
  needs: ['build@aarch64']
